"""Hooks for the demo collection. Every function is optional; see yss/hooks.py for the contract."""
from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent


def configure(collection: dict, cfg) -> dict:
    """Adjust collection.yaml data before anything is loaded (here: add a tag)."""
    tags = list(collection.get("tags") or [])
    if "hooked" not in tags:
        tags.append("hooked")
    collection["tags"] = tags
    return collection


def load_docs(collection: dict, cfg) -> list[dict]:
    """Generate a doc from data on disk - an inventory of the playable folder."""
    files = sorted(p.name for p in (HERE / "play").glob("*") if p.is_file())
    return [
        {
            "kind": "generic",
            "id": "inventory",
            "title": "Play folder inventory",
            "summary": "Generated by hooks.py at load time; lists the files that make up the playable.",
            "status": "active",
            "updated": "2026-09-02",
            "shape": "file-list",
            "data": [{"name": name, "mounted_at": f"play/{name}"} for name in files],
        }
    ]


def _notes(cfg, spec):
    play = HERE / "play"
    return {"files": [{"name": p.name, "bytes": p.stat().st_size} for p in sorted(play.glob("*")) if p.is_file()]}


providers = {"notes": _notes}


def after_build(cfg, target: str, out_dir: Path, collection: dict) -> None:
    """Write a marker file into this collection's output folder."""
    folder = Path(out_dir) / collection["id"]
    folder.mkdir(parents=True, exist_ok=True)
    (folder / "generated-by-hook.txt").write_text(f"target={target}\n", encoding="utf-8")
